Use builtin go buildinfo for git version information
superfly/flyctl pull request #2186
Opened 2023-04-26 16:29 UTC by mjsir911

This makes things more workable with offbeat build procedures eg package managers that might not fetch the repo from git, golang autoembeds this info when available & fails gracefully when not, or when manually requested with `-buildinfo=false` or `-buildvcs=false` (this is what gentoo does)

2023-04-26 16:32 UTC, kzys approved these changes

2023-04-26 16:44 UTC, dangra requested changes
The linter spotted some issues worth checking

2023-04-26 18:43 UTC, mjsir911 commented
yeah, clued me in on the tests for this. Unfortunately I can't think of an easy way to mock `debug.ReadBuildInfo()` so will just remove the git revision checking for now. Going to research how it's done elsewhere though.

2023-04-26 18:45 UTC, kzys commented
I'm fine not testing the commit part. We don't have much code around.

2023-04-26 20:27 UTC, dangra approved these changes

2023-04-26 22:06 UTC, tvdfly reviewed
Can we bring back the branch name for dev builds, though? It's helpful to see which branch something was built on when doing a bunch of local dev.

For example, this is what I have right now after running `make` on a branch:

```
% fly version
flyctl v0.0.0-1682385080+dev darwin/arm64 Commit: c62ae16a0a9fa41d3aedc56627632b7872bc4c95 (client-init-for-libs) BuildDate: 2023-04-25T01:11:20Z
```

we don't need (or probably want) the branch names in the builds that get released.

2023-04-27 18:04 UTC, mjsir911 commented
> Can we bring back the branch name for dev builds? It's helpful to see which branch something was built on when doing a bunch of local dev.
> 
> For example, this is what I have right now after running `make` on a branch:
> 
> ```
> % fly version
> flyctl v0.0.0-1682385080+dev darwin/arm64 Commit: c62ae16a0a9fa41d3aedc56627632b7872bc4c95 (client-init-for-libs) BuildDate: 2023-04-25T01:11:20Z
> ```
> 
> we don't need (or probably want) the branch names in the builds that get released.

Hey tvdfly,

Thanks for the request!, if this is a hard requirement on the version info, this PR is pretty much a non-starter.

The git command used to embed this data is revision (and timestamp) only: [`-c log.showsignature=false show -s --format=%H:%ct`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/cmd/go/internal/vcs/vcs.go;drc=bb3965695d3bc3586fba55c7b8d5e8a56cd4c0c9;l=340).

The go team does seem amenable to adding more detailed data into `buildinfo`, but that would be a pretty drawn out process.

Related issues:
- https://github.com/golang/go/issues/22147
- https://github.com/golang/go/issues/29814
- https://github.com/golang/go/issues/37475

I might end up filing a proposal to add branch name (or just custom information?)

Will let y'all close out this PR if you decide to, but thanks for considering it!

2023-05-04 18:36 UTC, tvdfly commented
What if we make our own branch var in the place we used to set the commit sha, and then set it in the makefile? If the var is set we can show it and if not we ignore it.

2023-05-12 01:52 UTC, mjsir911 commented
> What if we make our own branch var in the place we used to set the commit sha, and then set it in the makefile? If the var is set we can show it and if not we ignore it.

Part of the intent of the PR was moving this tagged-info logic outside of the makefile. Doing this works but brings us back to the same initial place where building without being inside of a git repo isn't supported nicely.

Could also sunset this PR and just make something to better handle git-less builds

2023-05-12 23:39 UTC, tvdfly commented
@mjsir911 I made a branch on top of this one with what I'm thinking: https://github.com/superfly/flyctl/commit/e2a6baf6

The branch name just doesn't show up if git isn't installed or doesn't work or whatever.

Is that still going to be a problem in the cases you outline? It doesn't seem like it to me, and I'm not very familiar with the issues the motivated the original change. Appreciate your help and this contribution!

2023-05-15 18:36 UTC, merged

2023-05-15 20:30 UTC, mjsir911 commented
> @mjsir911 I made a branch on top of this one with what I'm thinking: #2284 (this commit in particular: [e2a6baf6](https://github.com/superfly/flyctl/commit/e2a6baf6) )
> 
> The branch name just doesn't show up if git isn't installed or doesn't work or whatever.
> 
> Is that still going to be a problem in the cases you outline? It doesn't seem like it to me, and I'm not very familiar with the issues that motivated the original change. Appreciate your help and this contribution!

Sorry about the slow response, thanks for the merge! The change you linked makes everything work smoothly, yes.

I appreciate you working with me through this one.