migrate-to-v2: bugfix validate volumes after resolving them
superfly/flyctl pull request #2462
Opened 2023-06-20 20:47 UTC by tvdfly

previously, (at least some) migrations with volumes would not try to migrate the volumes, because the migration setup was not setting usesForkedVolumes. Now, we run the volume validation after resolving volumes to ensure it gets set correctly.

2023-06-20 21:54 UTC, alichay requested changes
Good catch! We should probably no longer call `validateVolumes` in `validate` then, right?

2023-06-20 21:57 UTC, tvdfly commented
> Good catch! We should probably no longer call `validateVolumes` in `validate` then, right?

I'm not really sure; this change made my migration with volumes work so I didn't investigate further. :-)

2023-06-20 22:08 UTC, alichay commented
shouldn't cause any issue to remove that original call then. if this function works when there's no volume state defined, that's a coincidence and shouldn't be depended on imo

2023-06-21 14:45 UTC, alichay approved these changes

2023-06-21 17:47 UTC, merged