Include whether or not we're using GPUs in command/stats
superfly/flyctl pull request #3289
Opened 2024-02-14 18:40 UTC by billyb2

### Change Summary

What and Why:
WE're now including whether or not a command is using a GPU in metrics, so we can more easily do some useful queries.

How:
We just check fly.toml to see if it contains gpu_kind anywhere. This should work for every command, but it'll be especially useful for deploys

Related to:

https://github.com/superfly/flyctl-metrics/pull/23

---

### Documentation

- [ ] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [ ] n/a

2024-02-14 20:04 UTC, dangra requested changes

2024-02-14 20:04 UTC, dangra commented on internal/command/command.go
> +		if compute != nil && compute.GPUKind != "" {
alternatively you can:

```go
instrument.UserGPU = lo.SomeBy(appConfig.Compute, func(x *appconfig.Compute) bool {
  return x != nil && x.MachineGuest != nil && x.MachineGuest.GPUKind != ""
})
```

2024-02-15 16:17 UTC, billyb2 commented on internal/cli/cli.go
> +	if cmd != nil {
And we want to always show that a command finish, even if it errored. We should probably incldue whether or not the command finishing was an error or not in command/stats though

2024-02-15 16:21 UTC, dangra approved these changes

2024-02-15 16:29 UTC, dangra commented on internal/command/command.go
> +	})
ignore me but had to suggest a simplification nitpick:

```suggestion
	if appConfig != nil {
		instrument.UsingGPU = lo.SomeBy(appConfig.Compute, func(x *appconfig.Compute) bool {
			return x != nil && x.MachineGuest != nil && x.MachineGuest.GPUKind != ""
		})
	}
```

2024-02-15 16:33 UTC, dangra commented on internal/command/command.go
> +	})
remove this

2024-02-15 16:38 UTC, billyb2 commented on internal/command/command.go
> +	})
forgot to stage removing this :(

2024-02-15 17:30 UTC, merged