Add proxy command
superfly/flyctl pull request #423
Opened 2021-06-05 19:06 UTC by rugwirobaker

This PR adds a new command `flyctl proxy <port[:port]>` that proxies
from a local port to a vm port over WireGuard.

This PR is still very raw:

* Needs help on context managament and graceful exists.
* Forgoes instance selection(for now).

2021-06-06 04:07 UTC, tqbf commented
So, this is great, but you probably want to base this PR on the `wireguard-agent` branch, and move some of the logic from the command to `pkg/agent/agent.go` (and `client.go`).

The reason for that is, you can only run one command that uses a given WireGuard connection at a time; if you run this proxy command right now, and, while the proxy is running, try to run `flyctl ssh console`, the `ssh` command will steal the WireGuard connection from the proxy, which will abruptly stop working.

The agent solves this problem by spawning a background process (you don't have to worry about how; you can just add new commands to the agent) that maintains a single WireGuard connection, but lets multiple runs of `flyctl` use that connection.

2021-06-06 04:12 UTC, tqbf commented
So, you'd want to add a function like this:

https://github.com/superfly/flyctl/blob/9d518cbfb7bbfca1e1a1e88ee4a7071457092007/pkg/agent/agent.go#L198

(notice that there's a helper, `tunnelFor`, which looks up the tunnel for a given WireGuard connection; you don't have to do the whole `StateForOrg` dance)

You want to add your helper to this map here:

https://github.com/superfly/flyctl/blob/9d518cbfb7bbfca1e1a1e88ee4a7071457092007/pkg/agent/agent.go#L55

... and now it's a part of the agent protocol.

Finally, you want to add it to the agent interface, which a function in `client.go` like this:

https://github.com/superfly/flyctl/blob/9d518cbfb7bbfca1e1a1e88ee4a7071457092007/pkg/agent/client.go#L125

Then, in `flyctl/cmd`, your command handler can call `EstablishFlyAgent` to get a `*Client` that it can use to talk to the agent (that function will spawn a new agent process if it's not already running; to debug your agent code, you can run it explicitly by running `flyctl agent daemon-start`; `EstablishFlyAgent` will talk to that agent if it's running.)

2021-06-06 04:14 UTC, tqbf commented
*Alternatively*: you can call `Client.DialContext` (see `client.go`) to get a function you can use to connect over WireGuard, using the agent, without modifying the agent protocol --- your proxy will still run entirely as a `flyctl` command, in the main `flyctl` process, but it'll use the agent to get new connections.

2021-07-14 22:49 UTC, mrkurt commented
@rugwirobaker how is this going? We have a couple of folks that might benefit it, so we can make a nice post when it's ready to merge.

2021-07-28 13:19 UTC, rugwirobaker commented
@tqbf @mrkurt  I'm about to move the proxy into the agent.

2021-08-20 13:26 UTC, rugwirobaker commented
@mrkurt @tqbf @michaeldwan I have moved the proxy inside the agent but we still have to implement it for no-agent and add a command to stop it when it's running in the background.

2021-08-23 08:34 UTC, rugwirobaker commented
Note that the proxy keeps serving existing TCP connection after `flyctl proxy stop` until the client stops them.

2021-09-24 16:08 UTC, michaeldwan requested changes
@rugwirobaker I just tried to run this and there's a compiler from changes to master.

I do think it would be wise to do as Thomas [suggested](https://github.com/superfly/flyctl/pull/423#issuecomment-855334384) and use a connection from the agent (just like the nats client) but run the actual proxy in the flyctl command. 

Running a proxy in the agent is a much more complicated ux since we need a stop command and some form of status so you can see what is actually being proxied, which this PR doesn't have yet. It also doesn't provide an easy way to see if the proxy is working since logs are hidden. We'd also need two implementations for the no-agent case. We're still working through reliability issues in the agent and I'd hate to add more to the pile. 

We can avoid most of that complexity by running the proxy in the flyctl command. When `flyctl proxy` starts, we get a connection from the agent and start the proxy. Output can be printed right to STDOUT so it's clear if it's working and what it's doing. Then when the command gets a SIGINT the proxy shuts down. 

Thoughts?

2021-09-24 19:30 UTC, michaeldwan requested changes
This looks and works great! Once the comments are addressed we can ship it.

2021-09-24 19:30 UTC, michaeldwan commented on helpgen/flyctlhelp.toml
> +shortHelp = "Commands creates a proxy to a fly app"
This message isn't clear. How about "Proxy connections to a fly app"?

2021-09-24 19:30 UTC, michaeldwan commented on pkg/agent/agent.go
> +	proxy         net.Listener
is this used?

2021-09-26 14:39 UTC, michaeldwan commented
@rugwirobaker almost 😄

Get rid of the `"Commands"` prefix on the help text string here since this one doesn't have any subcommands: https://github.com/superfly/flyctl/pull/423/commits/85de633bba900bad92d1f0627789003f38e79b58#diff-cd1f05056de04fa9945ef72198cde82f3c3d5132915b724b062f8a5ab86602a9R1031-R1032

2021-09-26 15:57 UTC, michaeldwan approved these changes
🎉

2021-09-27 15:07 UTC, merged