Postgres connect
superfly/flyctl pull request #471
Opened 2021-07-22 17:58 UTC by davissp14

Postgres connect allows you to quickly connect to a specified Postgres cluster.  

**TODO** 

I would like to streamline the authentication process for the default `postgres` user by hooking into the `OPERATOR_PASSWORD` environment variable.  

However, I am currently blocked by: https://github.com/superfly/flyctl/issues/463

```
Connect to a postgres cluster

Usage:
  flyctl postgres connect [flags]

Flags:
  -a, --app string        App name to operate on
  -c, --config string     Path to an app config file or directory containing one (default "./fly.toml")
      --database string   The postgres database to connect to
  -h, --help              help for connect
      --user string       The postgres user to connect with

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
  -v, --verbose               verbose output
 ```

2021-07-27 15:48 UTC, rugwirobaker commented
May I suggest a `user` flag? I may not want always connect with user `postgres`

2021-07-27 16:39 UTC, rugwirobaker commented
Never mind already exists

2021-12-07 12:54 UTC, jsierles commented
Should this be revisited or dropped in favor of new work?

2021-12-07 15:17 UTC, davissp14 commented
Now that SSH is more reliable, I should be able to add this pretty quickly.  I have it working for machines, so just a matter of creating a binary within the postgres-ha/postgres-standalone repos.

2021-12-10 05:40 UTC, davissp14 commented
This should be ready to go. 

I also added image version verification, which may be worth taking a glance at: https://github.com/superfly/flyctl/blob/864f5f5d7cb2d30112bcb325e12e46d1342c7113/cmd/postgres.go#L620-L653

<img width="766" alt="Screen Shot 2021-12-09 at 11 37 53 PM" src="https://user-images.githubusercontent.com/423038/145522915-11701bc9-5505-4d7c-ae2a-c81c5070659e.png">

2021-12-10 09:08 UTC, rugwirobaker commented on go.mod
> +	github.com/hashicorp/go-version v1.3.0 // indirect
This should be direct

2021-12-10 09:09 UTC, rugwirobaker requested changes

2021-12-10 09:09 UTC, rugwirobaker commented on go.mod
> +	github.com/hashicorp/go-version v1.3.0 // indirect
This should be direct

2021-12-10 17:11 UTC, merged