Add distinct name for WireGuard connections generated by the agent
superfly/flyctl pull request #492
Opened 2021-08-14 14:31 UTC by amalkh5

Fixes #465 

it will add the word "agent" to WireGuard connections generated by the agent, for example:
``` shell 
#  host-native WireGuard connections
$ interactive-amals-MacBook-amalkms5-gmail-com-724    

# agent WireGuard connections
$ agent-interactive-amals-MacBook-amalkms5-gmail-com-714
```

2021-08-15 09:18 UTC, amalkh5 commented
As for the failed checks, it was regreding existing code and I do not know if I should change it or keep it?

2021-10-01 10:50 UTC, rugwirobaker requested changes
Sorry for the late review. Everything looks except course the little deep source complaints. You can change those.

2021-10-01 16:56 UTC, amalkh5 commented
@rugwirobaker sorry I clicked on review by miskate, I will let you know when I fix the issues

2021-10-01 20:18 UTC, amalkh5 commented
@rugwirobaker 
I fixed all things suggested in deepsource except the one where it requests to change `math/rand` to `crypto/rand` because I [read](https://yourbasic.org/golang/crypto-rand-int/) that using `crypto/rand. Reader` returns an error if the underlying system call fails.
 For instance, if it can't read /dev/urandom on a Unix system, or if CryptAcquireContext fails on a Windows system.

What do you think?

2022-02-08 10:51 UTC, jsierles commented
Hey, would you be interested in finishing this up?

2022-02-08 11:06 UTC, amalkh5 commented
@jsierles sure, I will resolve the conflict and push it.

2022-02-08 14:19 UTC, amalkh5 commented
@jsierles  Fixed, I removed "interactive" and added the word "agent" to WireGuard connections generated and by the agent, for example:


```
# host-native WireGuard connections
$ interactive-amals-MacBook-xxx-amalxxxx-gmail-com-860    

# agent WireGuard connections
$ agent-amals-MacBook-xxx-amalxxxx-gmail-com-534
```

2022-02-08 14:32 UTC, jsierles requested changes

2022-02-08 14:32 UTC, jsierles commented on internal/wireguard/wg.go
> +func gernateConnectionnName(apiClient *api.Client, ctx context.Context) (string, error) {
This should be named correctly, perhaps with a better name like `generatePeerName`

2022-02-08 14:32 UTC, jsierles commented on internal/wireguard/wg.go
> +func gernateConnectionnName(apiClient *api.Client, ctx context.Context) (string, error) {
Also, the context should be the first argument passed in.

2022-02-09 18:46 UTC, amalkh5 commented
@jsierles fixed

2022-02-10 10:36 UTC, jsierles commented
Thanks! Actually we need to keep the name `interactive-`. Can you reverse it so we have something like `interactive-agent-*`?

2022-02-10 10:36 UTC, jsierles reviewed
Looks good except for the comment about keeping the `interactive-*` prefix.

2022-02-20 14:11 UTC, merged